config/routes.rb
Rails.application.routes.draw do

  devise_for :staffs, controllers: { sessions: "sessions" }

  scope ":consumer_id" do
    get '/', to: 'foos#index'

    get '/foos', to: 'foos#index'
    get '/foos/:id', to: 'foos#show'
  end

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :null_session
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_staff!
end

app/controllers/foos_controller.rb
class FoosController < AuthenticatedController
  
  skip_before_filter :authenticate_staff!, only: [:index]

  def index
  end

  def show
    @name = params[:id]
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foos/index.html.erb
<% if staff_signed_in? %>
      Logged In Hot Wheels
<% else %>
      Hot Wheels
<% end %>

app/views/foos/show.html.erb
<% if staff_signed_in? %>
      Logged in - <%= @name %>
<% else %>
      <%= @name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseEvaluation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if staff_signed_in? %>
  Logged in as <strong><%= current_staff.email %></strong>.
  <%= link_to 'Edit profile', edit_staff_registration_path %> |
  <%= link_to "Logout", destroy_staff_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_staff_registration_path %> |
  <%= link_to "Login", new_staff_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>